# -*- coding: utf-8 -*-
"""python_basics_Murali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Be86eiN-g0KS4O7hpnJDUcISE_stAuA5
"""

name = "Murali"
age = 22
height = 1.75
is_student = True

print(name, age, height, is_student)
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")
print(age * 12)
print(age * 365)
print(age % 7)
print(age ** 2)